# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tissad <tissad@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/06/24 12:19:33 by tissad            #+#    #+#              #
#    Updated: 2025/06/24 15:41:31 by tissad           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# This Dockerfile sets up a ModSecurity proxy server using Nginx and Alpine Linux.

FROM owasp/modsecurity:nginx-alpine